# Generated by Django 2.0 on 2018-01-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20180111_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitation',
            name='go_pages_count',
            field=models.IntegerField(default=0),
        ),
    ]
