# Generated by Django 2.0 on 2018-01-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_visitation_go_pages_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitation',
            name='go_pages_count',
        ),
    ]
