# Generated by Django 2.0 on 2018-01-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_auto_20180111_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ImageField(help_text='ВНИМАНИЕ! Для корректного отображения необходимо загружать изображения 760x350', upload_to='banner', verbose_name='Загрузка нового слайда')),
            ],
            options={
                'verbose_name': 'Слайд баннера',
                'verbose_name_plural': 'Слайды баннера',
            },
        ),
    ]
