# Generated by Django 2.0.1 on 2018-01-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Baskets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementbasket',
            options={'verbose_name': 'Элемент корзины', 'verbose_name_plural': 'Элементы корзины'},
        ),
    ]
