# Generated by Django 2.0 on 2018-01-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Baskets', '0003_merge_20180111_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementbasket',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterField(
            model_name='elementbasket',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
