# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='Ваше имя')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Ваша фамилия')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефона')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Улица')),
                ('house', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('building', models.IntegerField(blank=True, null=True, verbose_name='Строение/Владение/Корпус')),
                ('flat', models.IntegerField(blank=True, null=True, verbose_name='Номер квартиры/офиса')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Принадлежность')),
            ],
        ),
        migrations.CreateModel(
            name='FavoritesProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Пользователь')),
                ('products', models.ManyToManyField(to='Products.Product', verbose_name='Товары')),
            ],
        ),
    ]
