# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalRoom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluser',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер телефона'),
        ),
    ]
