# Generated by Django 2.0 on 2018-01-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalRoom', '0004_auto_20180110_1518'),
        ('PersonalRoom', '0004_auto_20180107_1318'),
    ]

    operations = [
    ]
