# Generated by Django 2.0 on 2018-01-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalRoom', '0005_merge_20180111_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='additionaluser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
