# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='Ваше имя')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Ваша фамилия')),
                ('phone', models.CharField(default='', max_length=12, verbose_name='Ваше номер телефона')),
                ('logistics', models.CharField(choices=[('courier', 'Курьер'), ('pickup', 'Самовывоз')], default='', max_length=20, verbose_name='Как доставить ваш заказ?')),
                ('payment', models.CharField(choices=[('Cash', 'Наличные'), ('Card', 'Карточка')], default='', max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('processed', 'Обрабатывается'), ('adopted', 'Принят')], default='processed', max_length=30)),
                ('city', models.CharField(default='', max_length=100, verbose_name='Город')),
                ('street', models.CharField(default='', max_length=200, verbose_name='Улица')),
                ('house', models.IntegerField(verbose_name='Номер дома')),
                ('building', models.IntegerField(blank=True, null=True, verbose_name='Строение/Владение/Корпус')),
                ('flat', models.IntegerField(blank=True, null=True, verbose_name='Номер квартиры/офиса')),
                ('comment', models.TextField(blank=True, default='')),
                ('username', models.CharField(default='AnonymousUser', max_length=200, verbose_name='Пользователь')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product', verbose_name='Товар')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='Orders.OrderItemProduct', verbose_name='Продукты'),
        ),
    ]
