# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='logistics',
        ),
    ]
