# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_auto_20171219_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logistic',
            field=models.CharField(choices=[('mail', 'Почта'), ('courier', 'Курьер')], default='', max_length=20, verbose_name='Доставка'),
        ),
    ]
