# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_order_logistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='logistic',
            field=models.CharField(choices=[('mail', 'Почта'), ('courier', 'Курьер'), ('cdek', 'Сдэк')], default='', max_length=20, verbose_name='Доставка'),
        ),
    ]
