# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_auto_20171219_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличные'), ('imposed', 'Наложенный'), ('card', 'Карта'), ('non-cash', 'Безналичный')], default='', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=16, verbose_name='Ваше номер телефона'),
        ),
    ]
