# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_order_amount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Обрабатывается'), ('adopted', 'Принят'), ('road', 'В дороге'), ('delivered', 'Доставлен')], default='processed', max_length=30),
        ),
    ]
