# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_auto_20171223_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Обрабатывается'), ('preparation', 'Подготовка к отправке'), ('road', 'В дороге'), ('delivered', 'Доставлен')], default='processed', max_length=30),
        ),
    ]
