# Generated by Django 2.0.1 on 2018-01-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0010_auto_20171228_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitemproduct',
            options={'verbose_name': 'Элемент заказа (продукты и их количество)', 'verbose_name_plural': 'Элементы заказа (продукты и их количество)'},
        ),
    ]
