# Generated by Django 2.0 on 2018-01-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0010_auto_20171228_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitemproduct',
            options={'verbose_name': 'Элемент заказа (продукты и их количество)', 'verbose_name_plural': 'Элементы заказа (продукты и их количество)'},
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Общая стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='logistic',
            field=models.CharField(choices=[('mail', 'Почта'), ('courier', 'Курьер'), ('cdek', 'Сдэк')], default='', max_length=20, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=16, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='Orders.OrderItemProduct', verbose_name='Продукты и их количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Обрабатывается'), ('preparation', 'Подготовка к отправке'), ('road', 'В дороге'), ('delivered', 'Доставлен')], default='processed', max_length=30, verbose_name='Статус'),
        ),
    ]
