# Generated by Django 2.0 on 2018-01-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0012_merge_20180111_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Ваша фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='logistic',
            field=models.CharField(choices=[('mail', 'Почта'), ('courier', 'Курьер'), ('cdek', 'Сдэк')], default='', max_length=20, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=16, verbose_name='Ваше номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='Orders.OrderItemProduct', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Обрабатывается'), ('preparation', 'Подготовка к отправке'), ('road', 'В дороге'), ('delivered', 'Доставлен')], default='processed', max_length=30),
        ),
    ]
