# Generated by Django 2.0 on 2018-01-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0013_auto_20180111_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitemproduct',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=16, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='orderitemproduct',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
