# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products', verbose_name='Выбери файлы. Можно выбрать несколько')),
            ],
            options={
                'verbose_name': 'Фотографии товара',
                'verbose_name_plural': 'Фотографии товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, verbose_name='Название')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('new_price', models.IntegerField(blank=True, null=True, verbose_name='Новая цена')),
                ('sail_procent', models.IntegerField(blank=True, null=True, verbose_name='Скидка')),
                ('availability', models.BooleanField(default=True, verbose_name='Доступность')),
                ('sold', models.PositiveIntegerField(default=0, verbose_name='Продано')),
                ('number', models.PositiveIntegerField(verbose_name='Количество в наличии')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('category', models.ManyToManyField(to='Products.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='SettingsProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteins', models.CharField(blank=True, max_length=30, null=True, verbose_name='Белки')),
                ('fats', models.CharField(blank=True, max_length=30, null=True, verbose_name='Жиры')),
                ('carbohydrates', models.CharField(blank=True, max_length=30, null=True, verbose_name='Углеводы')),
                ('caloric_value', models.CharField(blank=True, max_length=30, null=True, verbose_name='Калорийность')),
                ('net_weight', models.CharField(blank=True, max_length=30, null=True, verbose_name='Вес нетто')),
                ('packaging', models.CharField(blank=True, max_length=30, null=True, verbose_name='Упаковка')),
                ('shelf_life', models.CharField(blank=True, max_length=30, null=True, verbose_name='Срок хранения')),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Производитель')),
                ('manufacturer_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна производитель')),
                ('trademark', models.CharField(blank=True, max_length=50, null=True, verbose_name='Торговая марка')),
                ('product_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название продукта')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.SettingsProduct'),
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product', verbose_name='К какому товару причастны'),
        ),
    ]
