# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='settings',
        ),
        migrations.AddField(
            model_name='product',
            name='settings',
            field=models.ManyToManyField(to='Products.SettingsProduct'),
        ),
    ]
