# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20171206_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='settings',
        ),
        migrations.AddField(
            model_name='product',
            name='settings',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Products.SettingsProduct', verbose_name='Характеристики продукта'),
            preserve_default=False,
        ),
    ]
