# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20171206_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproduct',
            name='image_resize',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
