# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 14:37
from __future__ import unicode_literals

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_imageproduct_image_resize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(upload_to=Products.models.directory_path, verbose_name='Выбери файлы. Можно выбрать несколько'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
    ]
