# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20171210_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_url',
            field=models.CharField(default='tesst', max_length=500, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
