# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_product_name_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL'),
        ),
    ]
