# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_auto_20171210_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес'),
        ),
    ]
