# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_auto_20171222_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new',
        ),
    ]
