# Generated by Django 2.0.1 on 2018-01-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_auto_20171222_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingsproduct',
            options={'verbose_name': 'Характеристика продукта', 'verbose_name_plural': 'Характеристики продуктов'},
        ),
    ]
