# Generated by Django 2.0 on 2018-01-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_auto_20180111_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='category', to='Products.Category', verbose_name='Категория'),
        ),
    ]
